// The code in this file is generated!
// If you want to change it, update hack/gen.py
package v1

const (
	ARCCommand CommandTag = iota
	AllStereoCommand
	Analog1Command
	Analog2Command
	Analog3Command
	Analog4Command
	Analog5Command
	Analog71Command
	AutoCommand
	BackCommand
	BackTrimSetCommand
	BandAMCommand
	BandFMCommand
	BassDownCommand
	BassUpCommand
	CenterCommand
	CenterTrimSetCommand
	ChannelCommand
	Channel1Command
	Channel10Command
	Channel11Command
	Channel12Command
	Channel13Command
	Channel14Command
	Channel15Command
	Channel16Command
	Channel17Command
	Channel18Command
	Channel19Command
	Channel2Command
	Channel20Command
	Channel3Command
	Channel4Command
	Channel5Command
	Channel6Command
	Channel7Command
	Channel8Command
	Channel9Command
	Coax1Command
	Coax2Command
	Coax3Command
	Coax4Command
	DimCommand
	DIRACCommand
	DirectCommand
	DolbyCommand
	DownCommand
	DTSCommand
	EnterCommand
	FrequencyCommand
	FrontInCommand
	Hdmi1Command
	Hdmi2Command
	Hdmi3Command
	Hdmi4Command
	Hdmi5Command
	Hdmi6Command
	Hdmi7Command
	Hdmi8Command
	InfoCommand
	InputCommand
	InputDownCommand
	InputUpCommand
	LeftCommand
	LoudnessCommand
	LoudnessOffCommand
	LoudnessOnCommand
	MenuCommand
	ModeCommand
	ModeDownCommand
	ModeUpCommand
	MovieCommand
	MusicCommand
	MuteCommand
	MuteOffCommand
	MuteOnCommand
	NoneCommand
	Optical1Command
	Optical2Command
	Optical3Command
	Optical4Command
	PowerOffCommand
	PowerOnCommand
	Preset1Command
	Preset2Command
	ReferenceStereoCommand
	RightCommand
	SeekCommand
	SetVolumeCommand
	Source1Command
	Source2Command
	Source3Command
	Source4Command
	Source5Command
	Source6Command
	Source7Command
	Source8Command
	SourceTunerCommand
	SpeakerPresetCommand
	StandbyCommand
	SubwooferCommand
	SubwooferTrimSetCommand
	SurroundCommand
	SurroundTrimSetCommand
	TrebleDownCommand
	TrebleUpCommand
	TunerCommand
	UpCommand
	USBStreamCommand
	VolumeCommand
	Zone1BandCommand
	Zone2ARCCommand
	Zone2Analog1Command
	Zone2Analog2Command
	Zone2Analog3Command
	Zone2Analog4Command
	Zone2Analog5Command
	Zone2Analog71Command
	Zone2Analog8Command
	Zone2BandCommand
	Zone2Coax1Command
	Zone2Coax2Command
	Zone2Coax3Command
	Zone2Coax4Command
	Zone2EthernetCommand
	Zone2FollowMainCommand
	Zone2FrontInCommand
	Zone2InputCommand
	Zone2MuteCommand
	Zone2MuteOffCommand
	Zone2MuteOnCommand
	Zone2Optical1Command
	Zone2Optical2Command
	Zone2Optical3Command
	Zone2Optical4Command
	Zone2PowerCommand
	Zone2PowerOffCommand
	Zone2PowerOnCommand
	Zone2SetVolumeCommand
	Zone2VolumeCommand
)

var CommandTagStrings = []string{
	"ARC",
	"all_stereo",
	"analog1",
	"analog2",
	"analog3",
	"analog4",
	"analog5",
	"analog7.1",
	"auto",
	"back",
	"back_trim_set",
	"band_am",
	"band_fm",
	"bass_down",
	"bass_up",
	"center",
	"center_trim_set",
	"channel",
	"channel_1",
	"channel_10",
	"channel_11",
	"channel_12",
	"channel_13",
	"channel_14",
	"channel_15",
	"channel_16",
	"channel_17",
	"channel_18",
	"channel_19",
	"channel_2",
	"channel_20",
	"channel_3",
	"channel_4",
	"channel_5",
	"channel_6",
	"channel_7",
	"channel_8",
	"channel_9",
	"coax1",
	"coax2",
	"coax3",
	"coax4",
	"dim",
	"dirac",
	"direct",
	"dolby",
	"down",
	"dts",
	"enter",
	"frequency",
	"front_in",
	"hdmi1",
	"hdmi2",
	"hdmi3",
	"hdmi4",
	"hdmi5",
	"hdmi6",
	"hdmi7",
	"hdmi8",
	"info",
	"input",
	"input_down",
	"input_up",
	"left",
	"loudness",
	"loudness_off",
	"loudness_on",
	"menu",
	"mode",
	"mode_down",
	"mode_up",
	"movie",
	"music",
	"mute",
	"mute_off",
	"mute_on",
	"none",
	"optical1",
	"optical2",
	"optical3",
	"optical4",
	"power_off",
	"power_on",
	"preset1",
	"preset2",
	"reference_stereo",
	"right",
	"seek",
	"set_volume",
	"source_1",
	"source_2",
	"source_3",
	"source_4",
	"source_5",
	"source_6",
	"source_7",
	"source_8",
	"source_tuner",
	"speaker_preset",
	"standby",
	"subwoofer",
	"subwoofer_trim_set",
	"surround",
	"surround_trim_set",
	"treble_down",
	"treble_up",
	"tuner",
	"up",
	"usb_stream",
	"volume",
	"zone1_band",
	"zone2_ARC",
	"zone2_analog1",
	"zone2_analog2",
	"zone2_analog3",
	"zone2_analog4",
	"zone2_analog5",
	"zone2_analog71",
	"zone2_analog8",
	"zone2_band",
	"zone2_coax1",
	"zone2_coax2",
	"zone2_coax3",
	"zone2_coax4",
	"zone2_ethernet",
	"zone2_follow_main",
	"zone2_front_in",
	"zone2_input",
	"zone2_mute",
	"zone2_mute_off",
	"zone2_mute_on",
	"zone2_optical1",
	"zone2_optical2",
	"zone2_optical3",
	"zone2_optical4",
	"zone2_power",
	"zone2_power_off",
	"zone2_power_on",
	"zone2_set_volume",
	"zone2_volume",
}


const (
	AudioBitsNotification NotificationTag = iota
	AudioBitstreamNotification
	AudioInputNotification
	BackNotification
	CenterNotification
	DimNotification
	Input1Notification
	Input2Notification
	Input3Notification
	Input4Notification
	Input5Notification
	Input6Notification
	Input7Notification
	Input8Notification
	LoudnessNotification
	ModeNotification
	ModeAllStereoNotification
	ModeAutoNotification
	ModeDirectNotification
	ModeDolbyNotification
	ModeDTSNotification
	ModeMovieNotification
	ModeMusicNotification
	ModeRefStereoNotification
	ModeStereoNotification
	PowerNotification
	SourceNotification
	SpeakerPresetNotification
	SubwooferNotification
	SurroundNotification
	TunerRDSNotification
	TunerBandNotification
	TunerChannelNotification
	TunerProgramNotification
	TunerSignalNotification
	VideoFormatNotification
	VideoInputNotification
	VideoSpaceNotification
	VolumeNotification
	Zone2InputNotification
	Zone2PowerNotification
	Zone2VolumeNotification
)

var NotificationTagStrings = []string{
	"audio_bits",
	"audio_bitstream",
	"audio_input",
	"back",
	"center",
	"dim",
	"input_1",
	"input_2",
	"input_3",
	"input_4",
	"input_5",
	"input_6",
	"input_7",
	"input_8",
	"loudness",
	"mode",
	"mode_all_stereo",
	"mode_auto",
	"mode_direct",
	"mode_dolby",
	"mode_dts",
	"mode_movie",
	"mode_music",
	"mode_ref_stereo",
	"mode_stereo",
	"power",
	"source",
	"speaker_preset",
	"subwoofer",
	"surround",
	"tuner_RDS",
	"tuner_band",
	"tuner_channel",
	"tuner_program",
	"tuner_signal",
	"video_format",
	"video_input",
	"video_space",
	"volume",
	"zone2_input",
	"zone2_power",
	"zone2_volume",
}

